---
- hosts: all
  become: yes
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present
    - name: i want to create a file
      file:
        path: /home/ubuntu/mytestfile
        state: touch
